{% set name = "torchgeo" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchgeo-{{ version }}.tar.gz
  sha256: 218bd5aed7680244688dbf0f1398f5251ad243267eb19a6a7332668ac779a1cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=42
  run:
    - einops
    - fiona >=1.5
    - kornia >=0.5.11
    - matplotlib-base
    - numpy
    - omegaconf >=2.1
    - pillow >=2.9
    - pyproj >=2.2
    - python >=3.7
    - pytorch >=1.7
    - pytorch-lightning >=1.3
    - rasterio >=1.0.16
    - rtree >=0.9.4
    - scikit-learn >=0.18
    - segmentation-models-pytorch >=0.2
    - shapely >=1.3
    - timm >=0.2.1
    - torchmetrics >=0.7
    - torchvision >=0.10

test:
  imports:
    - torchgeo
    - torchgeo.datamodules
    - torchgeo.datasets
    - torchgeo.losses
    - torchgeo.models
    - torchgeo.samplers
    - torchgeo.trainers
    - torchgeo.transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/torchgeo
  doc_url: https://torchgeo.readthedocs.io/
  dev_url: https://github.com/microsoft/torchgeo
  license: MIT
  license_file: LICENSE
  summary: 'TorchGeo: datasets, transforms, and models for geospatial data'
  description: |
    TorchGeo is a PyTorch domain library, similar to torchvision, that provides datasets, transforms, samplers, and pre-trained models specific to geospatial data.

    The goal of this library is to make it simple

    1. for machine learning experts to use geospatial data in their workflows, and
    2. for remote sensing experts to use their data in machine learning workflows.

extra:
  recipe-maintainers:
    - adamjstewart
    - calebrob6
