{% set name = "torchgeo" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchgeo-{{ version }}.tar.gz
  sha256: 2bc2f9c4a19a569790cb3396499fdec17496632b0e52b86be390a2cc7a1a7033

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
    - setuptools >=42,<68
  run:
    - einops >=0.3,<0.7
    - fiona >=1.8,<2
    - kornia >=0.6.5,<0.7
    - lightning >=1.8,<3
    - matplotlib-base >=3.3,<4
    - numpy >=1.17.2,<2
    - pillow >=6.2,<10
    - pyproj >=2.2,<4
    - python >=3.7,<4
    - pytorch >=1.12,<3
    - rasterio >=1.0.20,<2
    - rtree >=1,<2
    - scikit-learn >=0.21,<2
    - segmentation-models-pytorch >=0.2,<0.4
    - shapely >=1.3,<3
    - timm >=0.4.12,<0.7
    - torchmetrics >=0.10,<0.12
    - torchvision >=0.13,<0.16

test:
  imports:
    - torchgeo
    - torchgeo.datamodules
    - torchgeo.datasets
    - torchgeo.losses
    - torchgeo.models
    - torchgeo.samplers
    - torchgeo.trainers
    - torchgeo.transforms
  #commands:
  #  - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/torchgeo
  doc_url: https://torchgeo.readthedocs.io/
  dev_url: https://github.com/microsoft/torchgeo
  license: MIT
  license_file: LICENSE
  summary: 'TorchGeo: datasets, samplers, transforms, and pre-trained models for geospatial data'
  description: |
    TorchGeo is a PyTorch domain library, similar to torchvision, providing datasets, samplers, transforms, and pre-trained models specific to geospatial data.

    The goal of this library is to make it simple

    1. for machine learning experts to work with geospatial data, and
    2. for remote sensing experts to explore machine learning solutions.

extra:
  recipe-maintainers:
    - adamjstewart
    - calebrob6
