{% set name = "torchgeo" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchgeo-{{ version }}.tar.gz
  sha256: c5b073b3c9ac06cd68e45620bab3a78fb7637fa3563aae4f75f4781ba57aee5a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61
  run:
    - python >=3.10
    - einops >=0.3
    - fiona >=1.8.21
    - kornia >=0.7.3
    - lightly >=1.4.5,!=1.4.26
    - lightning >=2,!=2.3.*
    - matplotlib-base >=3.5
    - numpy >=1.21.2
    - pandas >=1.3.3
    - pillow >=8.4
    - pyproj >=3.3
    - rasterio >=1.3
    - rtree >=1
    - segmentation-models-pytorch >=0.2
    - shapely >=1.8
    - timm >=0.4.12
    - pytorch >=1.13
    - torchmetrics >=0.10
    - torchvision >=0.14

    # Needed by LightningCLI
    - jsonargparse >=4.18
    - typeshed-client >=2.1
test:
  imports:
    - torchgeo
    - torchgeo.datamodules
    - torchgeo.datasets
    - torchgeo.losses
    - torchgeo.models
    - torchgeo.samplers
    # Uncomment when https://github.com/conda-forge/lightly-feedstock/issues/20 is resolved
    # - torchgeo.trainers
    - torchgeo.transforms
  commands:
    - pip check
    - python -m torchgeo --help
    - torchgeo --help
  requires:
    - pip

about:
  home: https://github.com/microsoft/torchgeo
  doc_url: https://torchgeo.readthedocs.io/
  dev_url: https://github.com/microsoft/torchgeo
  license: MIT
  license_file: LICENSE
  summary: 'TorchGeo: datasets, samplers, transforms, and pre-trained models for geospatial data'
  description: |
    TorchGeo is a PyTorch domain library, similar to torchvision, providing datasets, samplers, transforms, and pre-trained models specific to geospatial data.

    The goal of this library is to make it simple

    1. for machine learning experts to work with geospatial data, and
    2. for remote sensing experts to explore machine learning solutions.

extra:
  recipe-maintainers:
    - adamjstewart
    - calebrob6
    - isaaccorley
    - nilsleh
