{% set name = "torchgeo" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torchgeo-{{ version }}.tar.gz
  sha256: ba7a716843575d173abab383c6cc2d5fc8faf5834472f16a4abe1b932040ece5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4
    - setuptools >=42,<66
  run:
    - einops >=0.3,<0.5
    - fiona >=1.8,<2
    - kornia >=0.6.4,<0.7
    - matplotlib-base >=3.3,<4
    - numpy >=1.17.2,<2
    - omegaconf >=2.1,<3
    - packaging >=17,<22
    - pillow >=6.2,<10
    - pyproj >=2.2,<4
    - python >=3.7,<4
    - pytorch >=1.9,<2
    - pytorch-lightning >=1.5.1,<2
    - rasterio >=1.0.20,<2
    - rtree >=1,<2
    - scikit-learn >=0.21,<2
    - segmentation-models-pytorch >=0.2,<0.4
    - shapely >=1.3,<2
    - timm >=0.4.12,<0.5
    - torchmetrics >=0.7,<0.10
    - torchvision >=0.10,<0.14

test:
  imports:
    - torchgeo
    - torchgeo.datamodules
    - torchgeo.datasets
    - torchgeo.losses
    - torchgeo.models
    - torchgeo.samplers
    - torchgeo.trainers
    - torchgeo.transforms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/torchgeo
  doc_url: https://torchgeo.readthedocs.io/
  dev_url: https://github.com/microsoft/torchgeo
  license: MIT
  license_file: LICENSE
  summary: 'TorchGeo: datasets, samplers, transforms, and pre-trained models for geospatial data'
  description: |
    TorchGeo is a PyTorch domain library, similar to torchvision, providing datasets, samplers, transforms, and pre-trained models specific to geospatial data.

    The goal of this library is to make it simple

    1. for machine learning experts to work with geospatial data, and
    2. for remote sensing experts to explore machine learning solutions.

extra:
  recipe-maintainers:
    - adamjstewart
    - calebrob6
